In [1]:
import pandas as pd 
import numpy as np

In [5]:
df = pd.read_csv("01_Calendar Lookup.csv", encoding="latin1")
print(df)

          Date
0     1/1/2020
1     1/2/2020
2     1/3/2020
3     1/4/2020
4     1/5/2020
..         ...
907  6/26/2022
908  6/27/2022
909  6/28/2022
910  6/29/2022
911  6/30/2022

[912 rows x 1 columns]

In [6]:
df.head()

       Date
0  1/1/2020
1  1/2/2020
2  1/3/2020
3  1/4/2020
4  1/5/2020

In [7]:
print(df.columns)

Index(['Date'], dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    912 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.3 KB

In [9]:
df["Date"] = pd.to_datetime(df["Date"])

In [11]:
df["DateKey"] = df["Date"].dt.strftime("%Y%m%d")

In [12]:
df["Year"] = df["Date"].dt.year

In [13]:
df["Month"] = df["Date"].dt.month

In [14]:
df["MonthName"] = df["Date"].dt.month_name()

In [15]:
df["Quarter"] = df["Date"].dt.quarter

In [16]:
df["Weekday"] = df["Date"].dt.day_name()

In [17]:
df

          Date   DateKey  Year  Month MonthName  Quarter    Weekday
0   2020-01-01  20200101  2020      1   January        1  Wednesday
1   2020-01-02  20200102  2020      1   January        1   Thursday
2   2020-01-03  20200103  2020      1   January        1     Friday
3   2020-01-04  20200104  2020      1   January        1   Saturday
4   2020-01-05  20200105  2020      1   January        1     Sunday
..         ...       ...   ...    ...       ...      ...        ...
907 2022-06-26  20220626  2022      6      June        2     Sunday
908 2022-06-27  20220627  2022      6      June        2     Monday
909 2022-06-28  20220628  2022      6      June        2    Tuesday
910 2022-06-29  20220629  2022      6      June        2  Wednesday
911 2022-06-30  20220630  2022      6      June        2   Thursday

[912 rows x 7 columns]

In [18]:
df.to_excel("Clean Calender Date.xlsx" , index=False)