In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("02_AdventureWorks Customer Lookup.csv",encoding="latin1")
print(df)

                         CustomerKey Prefix  FirstName LastName  BirthDate  \
0                              11000    MR.        JON     YANG   4/8/1966
1                              11001    MR.     EUGENE    HUANG  5/14/1965
2                              11002    MR.      RUBEN   TORRES  8/12/1965
3                              11003    MS.    CHRISTY      ZHU  2/15/1968
4                              11004   MRS.  ELIZABETH  JOHNSON   8/8/1968
...                              ...    ...        ...      ...        ...
18149                          30---      m        NaN      NaN   1/1/1900
18150                          30---      m        NaN      NaN   1/1/1900
18151                            NaN    NaN        NaN      NaN        NaN
18152  Export date 20230101 14:59:17    NaN        NaN      NaN        NaN
18153          Source AW_Cust_Master    NaN        NaN      NaN        NaN

      MaritalStatus Gender                    EmailAddress  AnnualIncome  \
0                 M      M       jon24@adventure-works.com       90000.0
1                 S      M    eugene10@adventure-works.com       60000.0
2                 M      M     ruben35@adventure-works.com       60000.0
3                 S      F   christy12@adventure-works.com       70000.0
4                 S      F  elizabeth5@adventure-works.com       80000.0
...             ...    ...                             ...           ...
18149           NaN    NaN                             NaN           NaN
18150           NaN    NaN                             NaN           NaN
18151           NaN    NaN                             NaN           NaN
18152           NaN    NaN                             NaN           NaN
18153           NaN    NaN                             NaN           NaN

       TotalChildren EducationLevel    Occupation HomeOwner
0                2.0      Bachelors  Professional         Y
1                3.0      Bachelors  Professional         N
2                3.0      Bachelors  Professional         Y
3                0.0      Bachelors  Professional         N
4                5.0      Bachelors  Professional         Y
...              ...            ...           ...       ...
18149            NaN            NaN           NaN       NaN
18150            NaN            NaN           NaN       NaN
18151            NaN            NaN           NaN       NaN
18152            NaN            NaN           NaN       NaN
18153            NaN            NaN           NaN       NaN

[18154 rows x 13 columns]

In [6]:
df = df[df["CustomerKey"].astype(str).str.isnumeric()]

In [7]:
df.tail(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
18138,29474,MR.,JAIME,RAJE,10/4/1959,M,M,jaime36@adventure-works.com,20000.0,2.0,Partial College,Manual,N
18139,29475,MR.,JARED,WARD,9/23/1959,S,M,jared6@adventure-works.com,20000.0,2.0,Partial College,Manual,N
18140,29476,MRS.,ELIZABETH,BRADLEY,7/3/1959,M,F,elizabeth30@adventure-works.com,20000.0,2.0,Partial College,Manual,N
18141,29477,MR.,NEIL,RUIZ,7/6/1959,M,M,neil3@adventure-works.com,20000.0,2.0,Partial College,Manual,N
18142,29478,MR.,DARREN,CARLSON,5/25/1959,S,M,darren41@adventure-works.com,30000.0,3.0,Graduate Degree,Clerical,Y
18143,29479,MR.,TOMMY,TANG,7/4/1958,M,M,tommy2@adventure-works.com,30000.0,1.0,Graduate Degree,Clerical,Y
18144,29480,MRS.,NINA,RAJI,11/10/1960,S,F,nina21@adventure-works.com,30000.0,3.0,Graduate Degree,Clerical,Y
18145,29481,MR.,IVAN,SURI,1/5/1960,S,M,ivan0@adventure-works.com,30000.0,3.0,Graduate Degree,Clerical,N
18146,29482,MR.,CLAYTON,ZHANG,3/5/1959,M,M,clayton0@adventure-works.com,30000.0,3.0,Bachelors,Clerical,Y
18147,29483,MR.,JÉSUS,NAVARRO,12/8/1959,M,M,jésus9@adventure-works.com,30000.0,0.0,Bachelors,Clerical,Y

In [8]:
print(df["CustomerKey"].dtype)

object

In [9]:
df["CustomerKey"] = pd.to_numeric(
    df["CustomerKey"],
    errors="coerce"
)

In [10]:
df = df.dropna(subset=["CustomerKey"])

In [11]:
df["CustomerKey"] = df["CustomerKey"].astype(int)

In [12]:
print(df)

       CustomerKey Prefix  FirstName LastName   BirthDate MaritalStatus  \
0            11000    MR.        JON     YANG    4/8/1966             M
1            11001    MR.     EUGENE    HUANG   5/14/1965             S
2            11002    MR.      RUBEN   TORRES   8/12/1965             M
3            11003    MS.    CHRISTY      ZHU   2/15/1968             S
4            11004   MRS.  ELIZABETH  JOHNSON    8/8/1968             S
...            ...    ...        ...      ...         ...           ...
18143        29479    MR.      TOMMY     TANG    7/4/1958             M
18144        29480   MRS.       NINA     RAJI  11/10/1960             S
18145        29481    MR.       IVAN     SURI    1/5/1960             S
18146        29482    MR.    CLAYTON    ZHANG    3/5/1959             M
18147        29483    MR.      JÉSUS  NAVARRO   12/8/1959             M

      Gender                    EmailAddress  AnnualIncome  TotalChildren  \
0          M       jon24@adventure-works.com       90000.0            2.0
1          M    eugene10@adventure-works.com       60000.0            3.0
2          M     ruben35@adventure-works.com       60000.0            3.0
3          F   christy12@adventure-works.com       70000.0            0.0
4          F  elizabeth5@adventure-works.com       80000.0            5.0
...      ...                             ...           ...            ...
18143      M      tommy2@adventure-works.com       30000.0            1.0
18144      F      nina21@adventure-works.com       30000.0            3.0
18145      M       ivan0@adventure-works.com       30000.0            3.0
18146      M    clayton0@adventure-works.com       30000.0            3.0
18147      M      jésus9@adventure-works.com       30000.0            0.0

        EducationLevel    Occupation HomeOwner
0            Bachelors  Professional         Y
1            Bachelors  Professional         N
2            Bachelors  Professional         Y
3            Bachelors  Professional         N
4            Bachelors  Professional         Y
...                ...           ...       ...
18143  Graduate Degree      Clerical         Y
18144  Graduate Degree      Clerical         Y
18145  Graduate Degree      Clerical         N
18146        Bachelors      Clerical         Y
18147        Bachelors      Clerical         Y

[18148 rows x 13 columns]

In [13]:
df["FirstName"] = df["FirstName"].str.title()

df["LastName"] = df["LastName"].str.title()

In [14]:
print(df["Prefix"].unique())

['MR.' 'MS.' 'MRS.' nan]

In [15]:
df["Prefix"] = (
    df["Prefix"]
    .str.upper()
    .str.strip()
)

In [16]:
df["BirthDate"] = pd.to_datetime(
    df["BirthDate"],
    errors="coerce"
)

In [17]:
print(df["BirthDate"].dtype)

datetime64[ns]

In [18]:
df.isnull().sum()

CustomerKey         0
Prefix            130
FirstName           0
LastName            0
BirthDate           0
MaritalStatus       0
Gender            130
EmailAddress        0
AnnualIncome        0
TotalChildren       0
EducationLevel      0
Occupation          0
HomeOwner           0
dtype: int64

In [19]:
df[df["Prefix"].isnull()][["CustomerKey","Prefix","Gender"]]

       CustomerKey Prefix Gender
24           11025    NaN    NaN
34           11035    NaN    NaN
81           11082    NaN    NaN
228          11234    NaN    NaN
464          11475    NaN    NaN
...            ...    ...    ...
17655        28981    NaN    NaN
17673        28999    NaN    NaN
17806        29136    NaN    NaN
18012        29345    NaN    NaN
18112        29448    NaN    NaN

[130 rows x 3 columns]

In [20]:
df["Gender"].value_counts(dropna=False)

Gender
M      9126
F      8892
NaN     130
Name: count, dtype: int64

In [21]:
df["Prefix"].value_counts(dropna=False)

Prefix
MR.     9126
MRS.    6422
MS.     2470
NaN      130
Name: count, dtype: int64

In [22]:
pd.crosstab(df["Prefix"], df["Gender"])

Gender     F     M
Prefix
MR.        0  9126
MRS.    6422     0
MS.     2470     0

In [23]:
df["Gender"].value_counts(dropna=False)

df["Prefix"].value_counts(dropna=False)

pd.crosstab(df["Prefix"], df["Gender"])

Gender     F     M
Prefix
MR.        0  9126
MRS.    6422     0
MS.     2470     0

In [24]:
df[df["Gender"].isnull()][["CustomerKey","Prefix"]]

       CustomerKey Prefix
24           11025    NaN
34           11035    NaN
81           11082    NaN
228          11234    NaN
464          11475    NaN
...            ...    ...
17655        28981    NaN
17673        28999    NaN
17806        29136    NaN
18012        29345    NaN
18112        29448    NaN

[130 rows x 2 columns]

In [25]:
df[
    (df["Gender"].isnull()) &
    (df["Prefix"].isnull())
].shape

(130, 13)

In [26]:
df[df["Prefix"].isnull()].head(20)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
24,11025,NaN,Alejandro,Beck,1945-12-23,M,NaN,alejandro45@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
34,11035,NaN,Wendy,Dominguez,1948-02-24,M,NaN,wendy12@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
81,11082,NaN,Angela,Butler,1966-08-04,S,NaN,angela17@adventure-works.com,130000.0,0.0,Graduate Degree,Management,N
228,11234,NaN,Anna,Griffin,1952-11-19,S,NaN,anna46@adventure-works.com,70000.0,4.0,Partial College,Professional,Y
464,11475,NaN,Cesar,Subram,1978-10-09,S,NaN,cesar12@adventure-works.com,30000.0,0.0,High School,Manual,N
512,11526,NaN,Katherine,Diaz,1956-08-06,M,NaN,katherine48@adventure-works.com,40000.0,1.0,Partial College,Clerical,Y
608,11623,NaN,Angela,Perry,1973-06-27,S,NaN,angela10@adventure-works.com,50000.0,1.0,Graduate Degree,Skilled Manual,Y
627,11643,NaN,Naomi,Munoz,1970-07-27,M,NaN,naomi7@adventure-works.com,50000.0,1.0,Bachelors,Skilled Manual,Y
944,11965,NaN,Katie,She,1956-10-19,S,NaN,katie3@adventure-works.com,70000.0,2.0,High School,Skilled Manual,Y
1254,12276,NaN,Alisha,Shan,1970-07-13,M,NaN,alisha34@adventure-works.com,30000.0,0.0,Bachelors,Clerical,Y
1261,12283,NaN,Todd,Zeng,1969-08-10,S,NaN,todd19@adventure-works.com,20000.0,0.0,Partial College,Manual,Y
1278,12300,NaN,Adriana,Gonzalez,1946-07-18,S,NaN,adriana19@adventure-works.com,80000.0,5.0,Partial College,Professional,Y
1349,12372,NaN,Darren,Prasad,1963-09-18,S,NaN,darren12@adventure-works.com,60000.0,3.0,Bachelors,Professional,N
1420,12446,NaN,Jasmine,Hall,1957-08-03,M,NaN,jasmine21@adventure-works.com,40000.0,1.0,Partial College,Clerical,Y
1490,12517,NaN,Alexa,Watson,1977-08-25,S,NaN,alexa0@adventure-works.com,30000.0,0.0,Partial College,Clerical,N
1735,12765,NaN,Robyn,Gill,1954-05-20,M,NaN,robyn11@adventure-works.com,20000.0,2.0,Partial High School,Manual,N
1760,12790,NaN,Brandon,Kumar,1958-10-05,S,NaN,brandon25@adventure-works.com,60000.0,4.0,Graduate Degree,Skilled Manual,Y
1899,12936,NaN,Renee,Moreno,1965-03-27,S,NaN,renee6@adventure-works.com,40000.0,0.0,Bachelors,Professional,Y
2100,13138,NaN,Teresa,Alonso,1960-06-11,M,NaN,teresa8@adventure-works.com,70000.0,5.0,Partial College,Skilled Manual,Y
2399,13448,NaN,Catherine,Ward,1962-07-13,M,NaN,catherine11@adventure-works.com,130000.0,1.0,Bachelors,Management,Y

In [27]:
df[
    (df["Gender"].isnull()) &
    (df["Prefix"].isnull())
].shape

(130, 13)

In [28]:
df[df["Prefix"].isnull()].head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
24,11025,NaN,Alejandro,Beck,1945-12-23,M,NaN,alejandro45@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
34,11035,NaN,Wendy,Dominguez,1948-02-24,M,NaN,wendy12@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
81,11082,NaN,Angela,Butler,1966-08-04,S,NaN,angela17@adventure-works.com,130000.0,0.0,Graduate Degree,Management,N
228,11234,NaN,Anna,Griffin,1952-11-19,S,NaN,anna46@adventure-works.com,70000.0,4.0,Partial College,Professional,Y
464,11475,NaN,Cesar,Subram,1978-10-09,S,NaN,cesar12@adventure-works.com,30000.0,0.0,High School,Manual,N
512,11526,NaN,Katherine,Diaz,1956-08-06,M,NaN,katherine48@adventure-works.com,40000.0,1.0,Partial College,Clerical,Y
608,11623,NaN,Angela,Perry,1973-06-27,S,NaN,angela10@adventure-works.com,50000.0,1.0,Graduate Degree,Skilled Manual,Y
627,11643,NaN,Naomi,Munoz,1970-07-27,M,NaN,naomi7@adventure-works.com,50000.0,1.0,Bachelors,Skilled Manual,Y
944,11965,NaN,Katie,She,1956-10-19,S,NaN,katie3@adventure-works.com,70000.0,2.0,High School,Skilled Manual,Y
1254,12276,NaN,Alisha,Shan,1970-07-13,M,NaN,alisha34@adventure-works.com,30000.0,0.0,Bachelors,Clerical,Y

In [29]:
df = df.dropna(subset=["Gender", "Prefix"])

In [30]:
print(df)

       CustomerKey Prefix  FirstName LastName  BirthDate MaritalStatus Gender  \
0            11000    MR.        Jon     Yang 1966-04-08             M      M
1            11001    MR.     Eugene    Huang 1965-05-14             S      M
2            11002    MR.      Ruben   Torres 1965-08-12             M      M
3            11003    MS.    Christy      Zhu 1968-02-15             S      F
4            11004   MRS.  Elizabeth  Johnson 1968-08-08             S      F
...            ...    ...        ...      ...        ...           ...    ...
18143        29479    MR.      Tommy     Tang 1958-07-04             M      M
18144        29480   MRS.       Nina     Raji 1960-11-10             S      F
18145        29481    MR.       Ivan     Suri 1960-01-05             S      M
18146        29482    MR.    Clayton    Zhang 1959-03-05             M      M
18147        29483    MR.      Jésus  Navarro 1959-12-08             M      M

                         EmailAddress  AnnualIncome  TotalChildren  \
0           jon24@adventure-works.com       90000.0            2.0
1        eugene10@adventure-works.com       60000.0            3.0
2         ruben35@adventure-works.com       60000.0            3.0
3       christy12@adventure-works.com       70000.0            0.0
4      elizabeth5@adventure-works.com       80000.0            5.0
...                               ...           ...            ...
18143      tommy2@adventure-works.com       30000.0            1.0
18144      nina21@adventure-works.com       30000.0            3.0
18145       ivan0@adventure-works.com       30000.0            3.0
18146    clayton0@adventure-works.com       30000.0            3.0
18147      jésus9@adventure-works.com       30000.0            0.0

        EducationLevel    Occupation HomeOwner
0            Bachelors  Professional         Y
1            Bachelors  Professional         N
2            Bachelors  Professional         Y
3            Bachelors  Professional         N
4            Bachelors  Professional         Y
...                ...           ...       ...
18143  Graduate Degree      Clerical         Y
18144  Graduate Degree      Clerical         Y
18145  Graduate Degree      Clerical         N
18146        Bachelors      Clerical         Y
18147        Bachelors      Clerical         Y

[18018 rows x 13 columns]

In [31]:
df[df["Gender"].isnull()][["CustomerKey","Prefix"]]

Empty DataFrame
Columns: [CustomerKey, Prefix]
Index: []

In [32]:
df.to_excel("AdventureWorks Customer Lookup Cleaned.xlsx", index=False)

In [33]:
df["CustomerKey"].nunique()

18018

In [ ]:
missing_customers = (
    set(df["CustomerKey"])
    - set(df["CustomerKey"])
)

print("Missing Customer Keys:", len(missing_customers))

Missing Customer Keys: 0

In [5]:
df.head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,4/8/1966,M,M,jon24@adventure-works.com,90000.0,2.0,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,5/14/1965,S,M,eugene10@adventure-works.com,60000.0,3.0,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,8/12/1965,M,M,ruben35@adventure-works.com,60000.0,3.0,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,2/15/1968,S,F,christy12@adventure-works.com,70000.0,0.0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,8/8/1968,S,F,elizabeth5@adventure-works.com,80000.0,5.0,Bachelors,Professional,Y
5,11005,MR.,JULIO,RUIZ,8/5/1965,S,M,julio1@adventure-works.com,70000.0,0.0,Bachelors,Professional,Y
6,11007,MR.,MARCO,MEHTA,5/9/1964,M,M,marco14@adventure-works.com,60000.0,3.0,Bachelors,Professional,Y
7,11008,MRS.,ROBIN,VERHOFF,7/7/1964,S,F,rob4@adventure-works.com,60000.0,4.0,Bachelors,Professional,Y
8,11009,MR.,SHANNON,CARLSON,4/1/1964,S,M,shannon38@adventure-works.com,70000.0,0.0,Bachelors,Professional,N
9,11010,MS.,JACQUELYN,SUAREZ,2/6/1964,S,F,jacquelyn20@adventure-works.com,70000.0,0.0,Bachelors,Professional,N