In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("04_AdventureWorks Product Lookup.csv")
print(df)

     ProductKey  ProductSubcategoryKey  ProductSKU              ProductName  \
0           214                     31   HL-U509-R    Sport-100 Helmet, Red
1           215                     31     HL-U509  Sport-100 Helmet, Black
2           218                     23   SO-B909-M   Mountain Bike Socks, M
3           219                     23   SO-B909-L   Mountain Bike Socks, L
4           220                     31   HL-U509-B   Sport-100 Helmet, Blue
..          ...                    ...         ...                      ...
288         602                      5     BB-8107        ML Bottom Bracket
289         603                      5     BB-9108        HL Bottom Bracket
290         604                      2  BK-R19B-44       Road-750 Black, 44
291         605                      2  BK-R19B-48       Road-750 Black, 48
292         606                      2  BK-R19B-52       Road-750 Black, 52

               ModelName                                 ProductDescription  \
0              Sport-100  Universal fit, well-vented, lightweight , snap...
1              Sport-100  Universal fit, well-vented, lightweight , snap...
2    Mountain Bike Socks  Combination of natural and synthetic fibers st...
3    Mountain Bike Socks  Combination of natural and synthetic fibers st...
4              Sport-100  Universal fit, well-vented, lightweight , snap...
..                   ...                                                ...
288    ML Bottom Bracket       Aluminum alloy cups; large diameter spindle.
289    HL Bottom Bracket             Aluminum alloy cups and a hollow axle.
290             Road-750  Entry level adult bike; offers a comfortable r...
291             Road-750  Entry level adult bike; offers a comfortable r...
292             Road-750  Entry level adult bike; offers a comfortable r...

    ProductColor ProductSize ProductStyle  ProductCost  ProductPrice
0            Red           0            0      13.0863       34.9900
1          Black           0            0      12.0278       33.6442
2          White           M            U       3.3963        9.5000
3          White           L            U       3.3963        9.5000
4           Blue           0            0      12.0278       33.6442
..           ...         ...          ...          ...           ...
288          NaN           0            0      44.9506      101.2400
289          NaN           0            0      53.9416      121.4900
290        Black          44            U     343.6496      539.9900
291        Black          48            U     343.6496      539.9900
292        Black          52            U     343.6496      539.9900

[293 rows x 11 columns]

In [3]:
df.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,0,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,0,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,0,0,12.0278,33.6442

In [3]:
df.shape

(293, 11)

In [4]:
df.columns

Index(['ProductKey', 'ProductSubcategoryKey', 'ProductSKU', 'ProductName',
       'ModelName', 'ProductDescription', 'ProductColor', 'ProductSize',
       'ProductStyle', 'ProductCost', 'ProductPrice'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             293 non-null    int64
 1   ProductSubcategoryKey  293 non-null    int64
 2   ProductSKU             293 non-null    object
 3   ProductName            293 non-null    object
 4   ModelName              293 non-null    object
 5   ProductDescription     293 non-null    object
 6   ProductColor           243 non-null    object
 7   ProductSize            293 non-null    object
 8   ProductStyle           293 non-null    object
 9   ProductCost            293 non-null    float64
 10  ProductPrice           293 non-null    float64
dtypes: float64(2), int64(2), object(7)
memory usage: 25.3+ KB

In [6]:
df["ProductSize"].value_counts()

ProductSize
0     84
44    29
48    25
52    16
42    15
58    13
38    12
L     11
M     11
62    11
60    11
40    11
46    11
S      9
50     9
54     9
XL     3
56     2
70     1
Name: count, dtype: int64

In [7]:
df["ProductSize"].unique()

array(['0', 'M', 'L', 'S', 'XL', '62', '44', '48', '52', '56', '58', '60',
       '42', '46', '38', '40', '70', '50', '54'], dtype=object)

In [8]:
df.groupby("ProductSize")["ProductName"].count()

ProductSize
0     84
38    12
40    11
42    15
44    29
46    11
48    25
50     9
52    16
54     9
56     2
58    13
60    11
62    11
70     1
L     11
M     11
S      9
XL     3
Name: ProductName, dtype: int64

In [9]:
df[df["ProductSize"]== "0"][["ProductName", "ProductSize"]]

                 ProductName ProductSize
0      Sport-100 Helmet, Red           0
1    Sport-100 Helmet, Black           0
4     Sport-100 Helmet, Blue           0
5               AWC Logo Cap           0
95                   LL Fork           0
..                       ...         ...
244              HL Crankset           0
245                    Chain           0
287        LL Bottom Bracket           0
288        ML Bottom Bracket           0
289        HL Bottom Bracket           0

[84 rows x 2 columns]

In [10]:
df["ProductSize"] = df["ProductSize"].replace("0", "Not Applicable")

In [11]:
df

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,Not Applicable,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,Not Applicable,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,Not Applicable,0,12.0278,33.6442
...,...,...,...,...,...,...,...,...,...,...,...
288,602,5,BB-8107,ML Bottom Bracket,ML Bottom Bracket,Aluminum alloy cups; large diameter spindle.,NaN,Not Applicable,0,44.9506,101.2400
289,603,5,BB-9108,HL Bottom Bracket,HL Bottom Bracket,Aluminum alloy cups and a hollow axle.,NaN,Not Applicable,0,53.9416,121.4900
290,604,2,BK-R19B-44,"Road-750 Black, 44",Road-750,Entry level adult bike; offers a comfortable r...,Black,44,U,343.6496,539.9900
291,605,2,BK-R19B-48,"Road-750 Black, 48",Road-750,Entry level adult bike; offers a comfortable r...,Black,48,U,343.6496,539.9900
292,606,2,BK-R19B-52,"Road-750 Black, 52",Road-750,Entry level adult bike; offers a comfortable r...,Black,52,U,343.6496,539.9900

In [12]:
df.isnull().sum()

ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64

In [13]:
df[df["ProductColor"].isnull()][["ProductName", "ProductColor"]]

                      ProductName ProductColor
95                        LL Fork          NaN
96                        ML Fork          NaN
97                        HL Fork          NaN
98                     LL Headset          NaN
99                     ML Headset          NaN
100                    HL Headset          NaN
101        LL Mountain Handlebars          NaN
102        ML Mountain Handlebars          NaN
103        HL Mountain Handlebars          NaN
104            LL Road Handlebars          NaN
105            ML Road Handlebars          NaN
106            HL Road Handlebars          NaN
136                    Cable Lock          NaN
137                      Minipump          NaN
138                 Mountain Pump          NaN
139  Taillights - Battery-Powered          NaN
140        Headlights - Dual-Beam          NaN
141     Headlights - Weatherproof          NaN
163         Water Bottle - 30 oz.          NaN
164          Mountain Bottle Cage          NaN
165              Road Bottle Cage          NaN
166           Patch Kit/8 Patches          NaN
169           Hitch Rack - 4-Bike          NaN
170         Bike Wash - Dissolver          NaN
171         Fender Set - Mountain          NaN
172        All-Purpose Bike Stand          NaN
201       LL Mountain Seat/Saddle          NaN
202       ML Mountain Seat/Saddle          NaN
203       HL Mountain Seat/Saddle          NaN
204           LL Road Seat/Saddle          NaN
205           ML Road Seat/Saddle          NaN
206           HL Road Seat/Saddle          NaN
207        LL Touring Seat/Saddle          NaN
208        ML Touring Seat/Saddle          NaN
209        HL Touring Seat/Saddle          NaN
214            Mountain Tire Tube          NaN
215                Road Tire Tube          NaN
216             Touring Tire Tube          NaN
221              LL Mountain Tire          NaN
222              ML Mountain Tire          NaN
223              HL Mountain Tire          NaN
224                  LL Road Tire          NaN
225                  ML Road Tire          NaN
226                  HL Road Tire          NaN
227                  Touring Tire          NaN
239         LL Touring Handlebars          NaN
240         HL Touring Handlebars          NaN
287             LL Bottom Bracket          NaN
288             ML Bottom Bracket          NaN
289             HL Bottom Bracket          NaN

In [14]:
df["ProductColor"] = df["ProductColor"].fillna("NotApplicable")

In [15]:
df

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,Not Applicable,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,Not Applicable,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,Not Applicable,0,12.0278,33.6442
...,...,...,...,...,...,...,...,...,...,...,...
288,602,5,BB-8107,ML Bottom Bracket,ML Bottom Bracket,Aluminum alloy cups; large diameter spindle.,NotApplicable,Not Applicable,0,44.9506,101.2400
289,603,5,BB-9108,HL Bottom Bracket,HL Bottom Bracket,Aluminum alloy cups and a hollow axle.,NotApplicable,Not Applicable,0,53.9416,121.4900
290,604,2,BK-R19B-44,"Road-750 Black, 44",Road-750,Entry level adult bike; offers a comfortable r...,Black,44,U,343.6496,539.9900
291,605,2,BK-R19B-48,"Road-750 Black, 48",Road-750,Entry level adult bike; offers a comfortable r...,Black,48,U,343.6496,539.9900
292,606,2,BK-R19B-52,"Road-750 Black, 52",Road-750,Entry level adult bike; offers a comfortable r...,Black,52,U,343.6496,539.9900

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df["ProductKey"].duplicated().sum()

np.int64(0)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             293 non-null    int64
 1   ProductSubcategoryKey  293 non-null    int64
 2   ProductSKU             293 non-null    object
 3   ProductName            293 non-null    object
 4   ModelName              293 non-null    object
 5   ProductDescription     293 non-null    object
 6   ProductColor           293 non-null    object
 7   ProductSize            293 non-null    object
 8   ProductStyle           293 non-null    object
 9   ProductCost            293 non-null    float64
 10  ProductPrice           293 non-null    float64
dtypes: float64(2), int64(2), object(7)
memory usage: 25.3+ KB

In [19]:
df["ProductColor"].value_counts()

ProductColor
Black            88
NotApplicable    50
Red              37
Silver           36
Yellow           36
Blue             26
Multi             8
Silver/Black      7
White             4
Grey              1
Name: count, dtype: int64

In [20]:
df["ProductSize"].value_counts()

ProductSize
Not Applicable    84
44                29
48                25
52                16
42                15
58                13
38                12
L                 11
M                 11
62                11
60                11
40                11
46                11
S                  9
50                 9
54                 9
XL                 3
56                 2
70                 1
Name: count, dtype: int64

In [21]:
df.describe()

       ProductKey  ProductSubcategoryKey  ProductCost  ProductPrice
count  293.000000             293.000000   293.000000    293.000000
mean   441.552901              12.283276   413.661009    714.437357
std    108.064327               9.892831   517.611849    872.157258
min    214.000000               1.000000     0.856500      2.290000
25%    354.000000               2.000000    31.724400     63.500000
50%    457.000000              12.000000   199.375700    333.420000
75%    533.000000              17.000000   601.743700   1003.910000
max    606.000000              37.000000  2171.294200   3578.270000

In [22]:
df.to_excel("AdventureWorks Product Lookup.xlsx", index=False)

In [23]:
df["ProductStyle"].value_counts()

ProductStyle
U    174
0     84
W     28
M      7
Name: count, dtype: int64

In [32]:
df[df["ProductStyle"] == "0"][["ProductName", "ProductStyle"]]

                 ProductName ProductStyle
0      Sport-100 Helmet, Red            0
1    Sport-100 Helmet, Black            0
4     Sport-100 Helmet, Blue            0
95                   LL Fork            0
96                   ML Fork            0
..                       ...          ...
244              HL Crankset            0
245                    Chain            0
287        LL Bottom Bracket            0
288        ML Bottom Bracket            0
289        HL Bottom Bracket            0

[84 rows x 2 columns]

In [24]:
df["ProductStyle"] = df["ProductStyle"].replace({
    "U" : "Universal",
    "0" : "Not Applicable",
    "W" : "Women",
    "M" :"Men",
})

In [35]:
df

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,Not Applicable,Not Applicable,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,Not Applicable,Not Applicable,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,Universal,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,Universal,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,Not Applicable,Not Applicable,12.0278,33.6442
...,...,...,...,...,...,...,...,...,...,...,...
288,602,5,BB-8107,ML Bottom Bracket,ML Bottom Bracket,Aluminum alloy cups; large diameter spindle.,NotApplicable,Not Applicable,Not Applicable,44.9506,101.2400
289,603,5,BB-9108,HL Bottom Bracket,HL Bottom Bracket,Aluminum alloy cups and a hollow axle.,NotApplicable,Not Applicable,Not Applicable,53.9416,121.4900
290,604,2,BK-R19B-44,"Road-750 Black, 44",Road-750,Entry level adult bike; offers a comfortable r...,Black,44,Universal,343.6496,539.9900
291,605,2,BK-R19B-48,"Road-750 Black, 48",Road-750,Entry level adult bike; offers a comfortable r...,Black,48,Universal,343.6496,539.9900
292,606,2,BK-R19B-52,"Road-750 Black, 52",Road-750,Entry level adult bike; offers a comfortable r...,Black,52,Universal,343.6496,539.9900

In [25]:
df.to_excel("AdventureWorks Product Lookup.xlsx", index=False)

In [27]:
df["ProductKey"].nunique()

293

In [28]:
df["ProductSubcategoryKey"].unique()

array([31, 23, 19, 21, 14, 12,  2,  1, 10, 11,  4, 17, 22, 35, 34, 36, 33,
       24, 18, 20, 25, 28, 37, 26, 29, 30, 27, 32, 16,  9,  6, 15, 13,  8,
        7,  3,  5])

In [29]:
missing_subcategories = (
    set(df["ProductSubcategoryKey"])
    - set(df["ProductSubcategoryKey"])
)

print(missing_subcategories)

set()