In [1]:
import pandas as pd
import numpy as np

In [2]:
sales2020 = pd.read_csv("06_AdventureWorks Sales Data 2020.csv", encoding="latin1")
sales2020

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,1/1/2020,9/21/2019,SO45080,332,14657,1,1,1
1,1/1/2020,12/5/2019,SO45079,312,29255,4,1,1
2,1/1/2020,10/29/2019,SO45082,350,11455,9,1,1
3,1/1/2020,11/16/2019,SO45081,338,26782,6,1,1
4,1/2/2020,12/15/2019,SO45083,312,14947,10,1,1
...,...,...,...,...,...,...,...,...
2625,12/31/2020,11/29/2020,SO48728,354,13111,9,1,1
2626,12/31/2020,11/14/2020,SO48729,324,26563,9,1,1
2627,12/31/2020,12/2/2020,SO48724,340,20722,8,1,1
2628,12/31/2020,10/9/2020,SO48723,369,14944,7,1,1
2629,12/31/2020,11/22/2020,SO48726,383,24915,9,1,1

In [3]:
sales2021 = pd.read_csv("07_AdventureWorks Sales Data 2021.csv", encoding="latin1")
sales2021

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,1/1/2021,10/17/2020,SO48797,385,14335,1,1,1
1,1/1/2021,9/30/2020,SO48802,383,24923,9,1,1
2,1/1/2021,11/29/2020,SO48801,326,15493,1,1,1
3,1/1/2021,11/16/2020,SO48799,352,26708,4,1,1
4,1/1/2021,12/16/2020,SO48798,369,23332,9,1,1
...,...,...,...,...,...,...,...,...
23930,12/31/2021,12/11/2021,SO61111,591,17841,10,1,1
23931,12/31/2021,10/15/2021,SO61147,464,12146,4,4,2
23932,12/31/2021,11/4/2021,SO61147,528,12146,4,1,2
23933,12/31/2021,11/9/2021,SO61147,215,12146,4,3,1
23934,12/31/2021,11/16/2021,SO61147,537,12146,4,2,1

In [4]:
sales2022 = pd.read_csv("08_AdventureWorks Sales Data 2022.csv", encoding="latin1")
sales2022

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,1/1/2022,12/13/2021,SO61285,529,23791,1,2,2
1,1/1/2022,9/24/2021,SO61285,214,23791,1,3,1
2,1/1/2022,9/4/2021,SO61285,540,23791,1,1,1
3,1/1/2022,9/28/2021,SO61301,529,16747,1,2,2
4,1/1/2022,10/21/2021,SO61301,377,16747,1,1,1
...,...,...,...,...,...,...,...,...
29476,6/30/2022,3/22/2022,SO74143,477,28517,10,3,2
29477,6/30/2022,3/15/2022,SO74143,479,28517,10,2,1
29478,6/30/2022,4/8/2022,SO74143,606,28517,10,1,1
29479,6/30/2022,5/15/2022,SO74124,480,21676,7,2,2
29480,6/30/2022,5/4/2022,SO74124,538,21676,7,1,2

In [5]:
sales = pd.concat(
    [sales2020, sales2021, sales2022], ignore_index= True)

In [6]:
sales

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,1/1/2020,9/21/2019,SO45080,332,14657,1,1,1
1,1/1/2020,12/5/2019,SO45079,312,29255,4,1,1
2,1/1/2020,10/29/2019,SO45082,350,11455,9,1,1
3,1/1/2020,11/16/2019,SO45081,338,26782,6,1,1
4,1/2/2020,12/15/2019,SO45083,312,14947,10,1,1
...,...,...,...,...,...,...,...,...
56041,6/30/2022,3/22/2022,SO74143,477,28517,10,3,2
56042,6/30/2022,3/15/2022,SO74143,479,28517,10,2,1
56043,6/30/2022,4/8/2022,SO74143,606,28517,10,1,1
56044,6/30/2022,5/15/2022,SO74124,480,21676,7,2,2
56045,6/30/2022,5/4/2022,SO74124,538,21676,7,1,2

In [7]:
sales["OrderDate"] = pd.to_datetime(
    sales["OrderDate"]
)

sales["DateKey"] = sales["OrderDate"].dt.strftime("%Y%m%d")

In [8]:
sales

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity,DateKey
0,2020-01-01,9/21/2019,SO45080,332,14657,1,1,1,20200101
1,2020-01-01,12/5/2019,SO45079,312,29255,4,1,1,20200101
2,2020-01-01,10/29/2019,SO45082,350,11455,9,1,1,20200101
3,2020-01-01,11/16/2019,SO45081,338,26782,6,1,1,20200101
4,2020-01-02,12/15/2019,SO45083,312,14947,10,1,1,20200102
...,...,...,...,...,...,...,...,...,...
56041,2022-06-30,3/22/2022,SO74143,477,28517,10,3,2,20220630
56042,2022-06-30,3/15/2022,SO74143,479,28517,10,2,1,20220630
56043,2022-06-30,4/8/2022,SO74143,606,28517,10,1,1,20220630
56044,2022-06-30,5/15/2022,SO74124,480,21676,7,2,2,20220630
56045,2022-06-30,5/4/2022,SO74124,538,21676,7,1,2,20220630

In [9]:
sales.columns

Index(['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey',
       'TerritoryKey', 'OrderLineItem', 'OrderQuantity', 'DateKey'],
      dtype='object')

In [10]:
sales.to_excel("09_AdventureWorks Sales Data 2020-2022.xlsx", index=False)

In [11]:
sales["CustomerKey"].nunique()

17416

In [12]:
missing_customers = (
    set(sales["CustomerKey"])
    - set(sales["CustomerKey"])
)

print("Missing Customer Keys:", len(missing_customers))

Missing Customer Keys: 0

In [13]:
sales.shape

(56046, 9)

In [15]:
sales["CustomerKey"].dtype

dtype('int64')